"""Stable machine-readable error model.

Never leak raw SQL exceptions to callers. Every domain failure raises
`ParkingError` carrying a stable code + HTTP status; the API layer maps them.
"""

from __future__ import annotations


class ErrorCode:
    UNAUTHORIZED = "UNAUTHORIZED"
    OPERATOR_NOT_FOUND = "OPERATOR_NOT_FOUND"
    PARKING_TENANT_NOT_FOUND = "PARKING_TENANT_NOT_FOUND"
    PARKING_SITE_NOT_FOUND = "PARKING_SITE_NOT_FOUND"
    GATE_NOT_FOUND = "GATE_NOT_FOUND"
    INVALID_GATE_DIRECTION = "INVALID_GATE_DIRECTION"
    LANE_NOT_FOUND = "LANE_NOT_FOUND"
    INVALID_LANE = "INVALID_LANE"
    INVALID_PLATE = "INVALID_PLATE"
    INVALID_VEHICLE_TYPE = "INVALID_VEHICLE_TYPE"
    ACTIVE_SESSION_ALREADY_EXISTS = "ACTIVE_SESSION_ALREADY_EXISTS"
    SESSION_NOT_FOUND = "SESSION_NOT_FOUND"
    INVALID_SESSION_STATE = "INVALID_SESSION_STATE"
    TARIFF_PLAN_NOT_FOUND = "TARIFF_PLAN_NOT_FOUND"
    TARIFF_CONFIGURATION_INVALID = "TARIFF_CONFIGURATION_INVALID"
    LOST_TICKET_FEE_NOT_CONFIGURED = "LOST_TICKET_FEE_NOT_CONFIGURED"
    COMPLIMENTARY_NOT_ALLOWED = "COMPLIMENTARY_NOT_ALLOWED"
    CROSS_TENANT_ACCESS_DENIED = "CROSS_TENANT_ACCESS_DENIED"
    RESOURCE_ALREADY_EXISTS = "RESOURCE_ALREADY_EXISTS"
    OPERATOR_INVALID_ROLE = "OPERATOR_INVALID_ROLE"
    INTERNAL_ERROR = "INTERNAL_ERROR"
    # M4 gate runtime
    GATE_NOT_AVAILABLE = "GATE_NOT_AVAILABLE"
    LANE_NOT_AVAILABLE = "LANE_NOT_AVAILABLE"
    ENTRY_DENIED = "ENTRY_DENIED"
    IDEMPOTENCY_CONFLICT = "IDEMPOTENCY_CONFLICT"
    # M5 exit runtime
    EXIT_SESSION_NOT_FOUND = "EXIT_SESSION_NOT_FOUND"
    EXIT_NOT_ALLOWED = "EXIT_NOT_ALLOWED"
    PAYMENT_REQUIRED = "PAYMENT_REQUIRED"
    QUOTE_EXPIRED = "QUOTE_EXPIRED"
    # M6 payment runtime
    PAYMENT_ALREADY_SETTLED = "PAYMENT_ALREADY_SETTLED"
    PAYMENT_NOT_FOUND = "PAYMENT_NOT_FOUND"
    PAYMENT_AMOUNT_MISMATCH = "PAYMENT_AMOUNT_MISMATCH"
    PAYMENT_CALLBACK_INVALID = "PAYMENT_CALLBACK_INVALID"
    PAYMENT_CALLBACK_REPLAY = "PAYMENT_CALLBACK_REPLAY"
    PAYMENT_NOT_VERIFIED = "PAYMENT_NOT_VERIFIED"
    # M7 ANPR
    ANPR_EVENT_INVALID = "ANPR_EVENT_INVALID"
    ANPR_EVENT_DUPLICATE = "ANPR_EVENT_DUPLICATE"
    ANPR_EVENT_CONFLICT = "ANPR_EVENT_CONFLICT"
    ANPR_DEVICE_NOT_AUTHORIZED = "ANPR_DEVICE_NOT_AUTHORIZED"
    ANPR_LOW_CONFIDENCE = "ANPR_LOW_CONFIDENCE"
    # M8 device / barrier
    DEVICE_NOT_FOUND = "DEVICE_NOT_FOUND"
    DEVICE_NOT_AUTHORIZED = "DEVICE_NOT_AUTHORIZED"
    DEVICE_OFFLINE = "DEVICE_OFFLINE"
    DEVICE_COMMAND_INVALID = "DEVICE_COMMAND_INVALID"
    DEVICE_COMMAND_CONFLICT = "DEVICE_COMMAND_CONFLICT"
    BARRIER_NOT_AUTHORIZED = "BARRIER_NOT_AUTHORIZED"
    # M9 edge
    EDGE_NOT_AUTHORIZED = "EDGE_NOT_AUTHORIZED"
    EDGE_CONFIG_STALE = "EDGE_CONFIG_STALE"
    EDGE_EVENT_CONFLICT = "EDGE_EVENT_CONFLICT"
    EDGE_SEQUENCE_GAP = "EDGE_SEQUENCE_GAP"
    EDGE_CLOCK_SKEW = "EDGE_CLOCK_SKEW"


class ParkingError(Exception):
    """Base domain error with a stable machine-readable code."""

    def __init__(self, code: str, message: str, status: int = 400, details=None):
        super().__init__(message)
        self.code = code
        self.message = message
        self.status = status
        self.details = details

    def to_dict(self) -> dict:
        body: dict = {"code": self.code, "message": self.message}
        if self.details is not None:
            body["details"] = self.details
        return {"error": body}


def parking_error(code: str, message: str, status: int = 400, details=None) -> ParkingError:
    return ParkingError(code, message, status, details)
