from __future__ import annotations

from typing import Any


PUBLIC_PRODUCTS: list[dict[str, Any]] = [
    {
        "slug": "business_suite",
        "name": "Business Suite",
        "short_name": "Business",
        "short_summary": "Kelola penjualan, stok, cabang, restoran, laporan, dan integrasi bisnis dalam satu pusat operasional.",
        "summary": "Pusat operasional cloud dan offline-first untuk toko ritel, kafe, restoran, dan bisnis multi-cabang.",
        "category": "business",
        "home_badge": "Bisnis",
        "home_cta": "Buka Business Suite",
        "icon": "flow",
        "accent": "business",
        "direct_url": "/bisnis/",
        "public_url": "/bisnis/",
        "status": "Aktif",
        "status_class": "live",
        "requires_auth": True,
        "capabilities": [
            "Retail POS",
            "Restaurant KDS",
            "Inventory",
            "Multi-Cabang",
            "Finance",
            "Integrasi",
        ],
    },
    {
        "slug": "connect",
        "name": "BotConnector Connect",
        "short_name": "Connect",
        "short_summary": "Hubungkan TradingView ke MetaTrader atau Binance. Kelola webhook, EA, dan otomasi sinyal trading.",
        "summary": "Pusat konektivitas dan webhook router untuk otomasi trading cepat dan stabil.",
        "category": "connect",
        "home_badge": "Koneksi",
        "home_cta": "Buka Connect",
        "icon": "link",
        "accent": "connect",
        "direct_url": "/connect-v2/",
        "public_url": "/connect-v2/",
        "status": "Aktif",
        "status_class": "live",
        "requires_auth": True,
        "capabilities": [
            "TradingView webhook",
            "MetaTrader 5",
            "Binance",
            "EA MetaTrader 5",
        ],
    },
    {
        "slug": "drive",
        "name": "My Drive",
        "short_name": "Drive",
        "short_summary": "Simpan, kelola, dan bagikan file Anda di seluruh ekosistem layanan BotConnector.",
        "summary": "Penyimpanan file terintegrasi dan aman yang terhubung ke akun BotConnector Anda.",
        "category": "store",
        "home_badge": "Penyimpanan",
        "home_cta": "Buka My Drive",
        "icon": "drive",
        "accent": "drive",
        "direct_url": "/drive",
        "public_url": "/drive",
        "status": "Universal",
        "status_class": "live",
        "requires_auth": True,
        "capabilities": [
            "Penyimpanan aman",
            "File sharing",
            "Akses cloud",
            "Integrasi aplikasi",
        ],
    },
    {
        "slug": "parking",
        "name": "BotConnector Parking",
        "short_name": "Parking",
        "short_summary": "Kelola akses kendaraan, tarif, pembayaran, ANPR, perangkat gerbang, dan operasional parkir multi-lokasi dari satu sistem.",
        "summary": "Pusat operasional parkir modern: akses gerbang, tarif otomatis, ANPR kamera, pembayaran tunai/QRIS, dan gateway edge offline.",
        "category": "business",
        "home_badge": "Parkir",
        "home_cta": "Buka Parking",
        "icon": "flow",
        "accent": "business",
        "direct_url": "/parking/",
        "public_url": "/parking/",
        "status": "Aktif",
        "status_class": "live",
        "requires_auth": True,
        "capabilities": [
            "Akses Gerbang & Lane",
            "Tarif Parkir Otomatis",
            "ANPR Software Ready",
            "Edge Offline Gateway",
            "Laporan Pendapatan",
            "Audit & Rekap Shift",
        ],
    },
    # Legacy products (preserved for backwards-compatibility references without cluttering current catalog)
    {
        "slug": "studio",
        "name": "PowerPoint Studio",
        "short_name": "Presentation",
        "short_summary": "Buat presentasi profesional dengan AI dan ekspor hasil ke PowerPoint.",
        "summary": "Mulai dari ide atau prompt, susun outline, buat slide, lalu ekspor presentasi.",
        "category": "legacy",
        "home_badge": "Legacy",
        "home_cta": "Buka PowerPoint",
        "icon": "spark",
        "accent": "presentation",
        "direct_url": "/studio",
        "public_url": "/studio",
        "status": "Legacy",
        "status_class": "legacy",
        "legacy": True,
        "requires_auth": False,
        "capabilities": ["AI presentation", "PPTX export"],
    },
    {
        "slug": "workspace",
        "name": "AI Workspace",
        "short_name": "Workspace",
        "short_summary": "Belajar, coding, dan selesaikan pekerjaan dengan AI dalam satu workspace.",
        "summary": "Gunakan Study AI, Coding AI, dan alat kerja berbasis AI dalam satu ruang.",
        "category": "legacy",
        "home_badge": "Legacy",
        "home_cta": "Buka Workspace",
        "icon": "flow",
        "accent": "workspace",
        "direct_url": "/workspace/",
        "public_url": "/workspace/",
        "status": "Legacy",
        "status_class": "legacy",
        "legacy": True,
        "requires_auth": False,
        "capabilities": ["Study AI", "Coding AI"],
    },
    {
        "slug": "photo",
        "name": "Photo Studio",
        "short_name": "Photo",
        "short_summary": "Edit, tingkatkan, dan olah foto dengan alat AI dalam satu studio visual.",
        "summary": "Hapus background, tingkatkan kualitas, olah foto produk, dan gunakan alat AI visual.",
        "category": "legacy",
        "home_badge": "Legacy",
        "home_cta": "Buka Photo Studio",
        "icon": "camera",
        "accent": "photo",
        "direct_url": "/photo-ai/",
        "public_url": "/photo-ai/",
        "status": "Legacy",
        "status_class": "legacy",
        "legacy": True,
        "requires_auth": False,
        "capabilities": ["Remove background", "Enhance"],
    },
    {
        "slug": "document",
        "name": "Document Assistant",
        "short_name": "Document",
        "short_summary": "Konversi, edit, OCR, rapikan, dan amankan dokumen dalam satu ruang kerja.",
        "summary": "Kelola PDF, Word, Excel, OCR, scan, tulisan tangan, dan berbagai kebutuhan dokumen.",
        "category": "legacy",
        "home_badge": "Legacy",
        "home_cta": "Buka Document",
        "icon": "document",
        "accent": "document",
        "direct_url": "/document-assistant/",
        "public_url": "/document-assistant/",
        "status": "Legacy",
        "status_class": "legacy",
        "legacy": True,
        "requires_auth": False,
        "capabilities": ["PDF tools", "OCR"],
    },
    {
        "slug": "spreadsheet",
        "name": "Spreadsheet Assistant",
        "short_name": "Spreadsheet",
        "short_summary": "Analisis, bersihkan, hitung, dan rapikan data spreadsheet dengan bantuan AI.",
        "summary": "Bekerja dengan workbook, formula, analisis, cleaning, dan dashboard data.",
        "category": "legacy",
        "home_badge": "Legacy",
        "home_cta": "Buka Spreadsheet",
        "icon": "table",
        "accent": "spreadsheet",
        "direct_url": "/document-assistant/spreadsheet/",
        "public_url": "/document-assistant/spreadsheet/",
        "status": "Legacy",
        "status_class": "legacy",
        "legacy": True,
        "requires_auth": False,
        "capabilities": ["Workbook analysis", "Data cleaning"],
    },
    {
        "slug": "intelligence",
        "name": "Document Intelligence",
        "short_name": "Intelligence",
        "short_summary": "Tanya, cari, rangkum, dan pahami informasi penting dari dokumen.",
        "summary": "Gunakan AI untuk summary, Q&A, translation, OCR, dan pemahaman dokumen.",
        "category": "legacy",
        "home_badge": "Legacy",
        "home_cta": "Buka Intelligence",
        "icon": "brain",
        "accent": "intelligence",
        "direct_url": "/document-assistant/intelligence/",
        "public_url": "/document-assistant/intelligence/",
        "status": "Legacy",
        "status_class": "legacy",
        "legacy": True,
        "requires_auth": False,
        "capabilities": ["Document Q&A", "Summary"],
    },
]


PUBLIC_PRODUCT_MAP: dict[str, dict[str, Any]] = {
    product["slug"]: product
    for product in PUBLIC_PRODUCTS
}


def _group(
    slug: str,
    eyebrow: str,
    title: str,
    description: str,
    product_slugs: list[str],
) -> dict[str, Any]:
    return {
        "slug": slug,
        "eyebrow": eyebrow,
        "title": title,
        "description": description,
        "product_slugs": product_slugs,
        "products": [
            PUBLIC_PRODUCT_MAP[item]
            for item in product_slugs
            if item in PUBLIC_PRODUCT_MAP
        ],
    }


PUBLIC_GROUPS: list[dict[str, Any]] = [
    _group(
        "business",
        "OPERASIONAL BISNIS",
        "Business Suite",
        "Pusat operasional bisnis untuk ritel, restoran, kasir POS, stok, dan multi-cabang.",
        ["business_suite"],
    ),
    _group(
        "parking",
        "OPERASIONAL PARKIR",
        "BotConnector Parking",
        "Kelola akses kendaraan, tarif, pembayaran, ANPR, gerbang, dan operasional parkir multi-lokasi.",
        ["parking"],
    ),
    _group(
        "connect",
        "KONEKSI & OTOMASI",
        "BotConnector Connect",
        "Hubungkan TradingView ke MetaTrader 5, Binance, dan otomasi sinyal trading.",
        ["connect"],
    ),
    _group(
        "store",
        "PENYIMPANAN",
        "My Drive",
        "Penyimpanan file terintegrasi untuk seluruh aplikasi dan dokumen BotConnector Anda.",
        ["drive"],
    ),
]
