const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const fmtBytes=n=>{n=Number(n||0);if(!n)return '—';const u=['B','KB','MB','GB','TB'];let i=0;while(n>=1024&&i<u.length-1){n/=1024;i++}return `${n.toFixed(i>1?2:0)} ${u[i]}`};
const fmtCount=n=>{n=Number(n||0);if(n>=1e6)return `${(n/1e6).toFixed(1)}M`;if(n>=1e3)return `${(n/1e3).toFixed(1)}K`;return String(n)};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const short=s=>String(s||'').replace(/\(R\)|\(TM\)/g,'').replace(/CPU\s*@.*$/i,'').trim();
const safePct=(a,b)=>b?Math.min(100,Math.max(0,Math.round(a/b*100))):0;
let state={hardware:null,runtime:{running:false},settings:{},managedRuntime:{installed:false},installed:[],downloads:[],preferredLanguages:[]};
let currentView='home',language='en',cap='all',discoverTab='trending',discoverAll=[],discoverBusy=false,currentDetails=null,chatMessages=[],chatAttachment=null,chatRequestId=null;
const pageHeaders=()=>window.BotI18n.t(language,'headers');
function tr(path){return window.BotI18n.t(language,path)}
function applyLanguage(){language=window.BotI18n.resolve(state.settings?.language||'system',state.preferredLanguages||[]);document.documentElement.lang=language;$$('[data-i18n]').forEach(el=>{const v=tr(el.dataset.i18n);if(typeof v==='string')el.textContent=v});setHeader(currentView)}
function setHeader(v){const h=window.BotI18n.t(language,`headers.${v}`);if(Array.isArray(h)){ $('#pageTitle').textContent=h[0];$('#pageSub').textContent=h[1]}}
function fitLabel(level){return ({great:'Great fit',ok:'Fits',warn:'Tight',no:'Does not fit',unknown:'Unknown'})[level]||'Unknown'}
function fitClass(level){return ['warn','no','unknown'].includes(level)?level:''}
function caps(c={}){return Object.entries({chat:'Chat',tools:'Tools',vision:'Vision',coding:'Coding',reasoning:'Reasoning',embeddings:'Embeddings',audio:'Audio'}).filter(([k])=>c[k]).map(([k,v])=>`<span class="cap ${k}">${v}</span>`).join('')||'<span class="cap">General</span>'}
function resolvedBackend(){const s=state.settings?.runtimeBackend||'auto';if(s!=='auto')return s;if(state.hardware?.nvidia?.length)return 'cuda12';return 'vulkan'}
function modelStorageBytes(){return state.installed.reduce((n,m)=>n+Number(m.size||0),0)}
function activeJobs(){return state.downloads.filter(j=>['downloading','pausing'].includes(j.status))}
function renderGlobal(){
 const h=state.hardware||{},gpu=h.nvidia?.[0];$('#sideDevice').textContent=gpu?.name||short(h.cpu)||'This device';$('#sideMemory').textContent=`${h.ramGb||'?'} GB RAM${gpu?` · ${gpu.memoryGb} GB VRAM`:''}`;
 const r=$('#runtimeStatus');if(state.runtime?.running){r.classList.add('running');r.innerHTML=`<i></i> ${tr('status.running')} · PID ${state.runtime.pid}`}else{r.classList.remove('running');r.innerHTML=`<i></i> ${tr('status.stopped')}`}
 const n=activeJobs().length;$('#downloadBadge').hidden=!n;$('#downloadBadge').textContent=n;renderHome();renderInstalled();renderDownloads();renderRuntime();renderSettings();renderChatHeader();
}
function renderHome(){
 const h=state.hardware||{},gpu=h.nvidia?.[0];$('#homeRuntime').textContent=state.runtime?.running?'Running':'Stopped';$('#homeRuntimeSub').textContent=state.runtime?.running?`PID ${state.runtime.pid}`:'No process';$('#homeInstalled').textContent=state.installed.length;$('#homeInstalledSub').textContent=`${fmtBytes(modelStorageBytes())} on disk`;$('#homeDownloads').textContent=activeJobs().length;$('#homeDownloadsSub').textContent=activeJobs().length?'Transfer active':'No active jobs';
 $('#modelsDirHome').textContent=state.settings?.modelsDir||'—';$('#hfStatus').textContent=state.settings?.hfTokenConfigured?'Token configured':'Public repositories only';$('#managedStatusHome').textContent=state.managedRuntime?.installed?'Installed':'Not installed';
 $('#specTable').innerHTML=`<div><span>CPU</span><b>${esc(short(h.cpu)||'—')}</b></div><div><span>Logical cores</span><b>${h.logicalCores||'—'}</b></div><div><span>System RAM</span><b>${h.ramGb||'—'} GB total · ${h.freeRamGb||'—'} GB free</b></div><div><span>NVIDIA GPU</span><b>${esc(gpu?`${gpu.name} · ${gpu.memoryGb} GB VRAM`:'Not detected')}</b></div><div><span>Platform</span><b>${esc(`${h.platform||'—'} ${h.arch||''}`)}</b></div><div><span>Preferred backend</span><b>${esc(resolvedBackend())}</b></div>`;
 const rec=recommendedModels().slice(0,5);$('#homeRecommendations').innerHTML=rec.length?rec.map(modelRow).join(''):'<div class="empty">No live recommendations loaded yet. Open Discover or wait for the initial catalog request.</div>';bindModelOpen($('#homeRecommendations'));
}
function recommendedModels(){const rank={great:0,ok:1,warn:2};return discoverAll.filter(m=>['great','ok','warn'].includes(m.compatibility?.level)).sort((a,b)=>(rank[a.compatibility?.level]-rank[b.compatibility?.level])||Number(b.trendingScore||0)-Number(a.trendingScore||0)||Number(b.downloads||0)-Number(a.downloads||0))}
function visibleDiscover(){let rows=discoverTab==='recommended'?recommendedModels():discoverAll;if(cap!=='all')rows=rows.filter(m=>m.capabilities?.[cap]);const q=$('#discoverSearch')?.value.trim().toLowerCase();if(q)rows=rows.filter(m=>[m.id,m.author,m.pipeline_tag,...(m.tags||[])].join(' ').toLowerCase().includes(q));return rows}
function modelRow(m){const name=String(m.id).split('/').pop(),publisher=m.author||String(m.id).split('/')[0],c=m.compatibility||{};return `<article class="model-row"><div class="model-icon">${esc(name[0]||'M')}</div><div class="model-main"><div class="model-title-line"><h3 title="${esc(m.id)}">${esc(m.id)}</h3><span class="fit ${fitClass(c.level)}">${fitLabel(c.level)}</span></div><div class="caps">${caps(m.capabilities)}</div><div class="model-meta"><span>${esc(publisher)}</span><span>${esc(m.pipeline_tag||'GGUF')}</span><span>${fmtCount(m.downloads)} downloads</span>${c.paramsB?`<span>${c.paramsB}B params</span>`:''}${c.estimatedQ4Gb?`<span>Q4 est. ${c.estimatedQ4Gb} GB</span>`:''}</div></div><div class="model-action"><span class="size">♥ ${m.likes||0}</span><button class="ghost" data-model-open="${esc(m.id)}">Details</button></div></article>`}
function bindModelOpen(root=document){root.querySelectorAll('[data-model-open]').forEach(b=>b.onclick=()=>openModel(b.dataset.modelOpen))}
async function loadDiscover(query=''){
 if(discoverBusy)return;discoverBusy=true;$('#discoverStatus').textContent=query?'Searching Hugging Face…':'Loading trending GGUF repositories…';
 try{discoverAll=await window.botconnector.searchModels({query,limit:100});$('#discoverStatus').textContent=`${discoverAll.length} GGUF repositories loaded from Hugging Face.`}catch(e){discoverAll=[];$('#discoverStatus').textContent=`Hugging Face request failed: ${e.message||e}`}
 discoverBusy=false;renderDiscover();renderHome();
}
function renderDiscover(){const rows=visibleDiscover();$('#discoverCount').textContent=`${rows.length} models`;$('#discoverModels').innerHTML=rows.length?rows.map(modelRow).join(''):'<div class="empty">No models match the current filter.</div>';bindModelOpen($('#discoverModels'))}
function memoryFitByBytes(bytes){const gb=Number(bytes||0)/1024**3,h=state.hardware||{},vram=Math.max(0,...(h.nvidia||[]).map(x=>Number(x.memoryGb||0))),reserve=Math.max(4,Math.min(8,Number(h.ramGb||0)*.25)),ram=Math.max(0,Number(h.ramGb||0)-reserve),budget=ram+vram*.55;if(!gb)return{level:'unknown',text:'Size unknown'};if(gb<=Math.max(vram*.9,ram*.7))return{level:'great',text:'Recommended'};if(gb<=ram)return{level:'ok',text:'Fits in system RAM'};if(gb<=budget)return{level:'warn',text:'Tight / partial offload'};return{level:'no',text:'Too large for current memory budget'}}
async function openModel(id){
 const modal=$('#modelModal'),body=$('#modelModalBody');modal.hidden=false;body.innerHTML='<div class="empty">Loading repository files from Hugging Face…</div>';
 try{currentDetails=await window.botconnector.modelDetails(id);renderModelDetails()}catch(e){body.innerHTML=`<div class="empty status-error">Failed to load model details: ${esc(e.message||e)}</div>`}
}
function renderModelDetails(){const m=currentDetails,body=$('#modelModalBody');if(!m)return;const c=m.compatibility||{};let recommendedIndex=-1;const rows=m.files.map((g,i)=>{const f=memoryFitByBytes(g.size);if(recommendedIndex<0&&['great','ok'].includes(f.level)&&/Q4_K_M|Q4_K|Q5_K_M|Q4_0/i.test(g.quant))recommendedIndex=i;return{...g,fit:f,index:i}});if(recommendedIndex<0)recommendedIndex=rows.find(x=>['great','ok'].includes(x.fit.level))?.index??-1;const projectorOptions=['<option value="">No projector</option>',...(m.projectors||[]).map((p,i)=>`<option value="${i}">${esc(p.path)} · ${fmtBytes(p.size)}</option>`)];body.innerHTML=`<div class="modal-head"><span class="kicker">HUGGING FACE REPOSITORY</span><h2>${esc(m.id)}</h2><div class="caps">${caps(m.capabilities)}</div><p class="technical-note">Exact GGUF file sizes below are read from the repository tree. Memory fit still remains an estimate because context/KV cache and backend allocation are runtime-dependent.</p></div><div class="modal-grid"><div><div class="quant-table">${rows.length?rows.map(r=>`<div class="quant-row"><code>${esc(r.quant)}</code><b>${fmtBytes(r.size)}</b><span class="quant-fit ${r.fit.level==='no'?'status-error':r.fit.level==='warn'?'status-warn':'status-ok'}">${esc(r.fit.text)}${r.index===recommendedIndex?' · default':''}${r.parts.length>1?` · ${r.parts.length} shards`:''}</span><button class="${r.index===recommendedIndex?'primary':'ghost'}" data-download-group="${r.index}">Download</button></div>`).join(''):'<div class="empty">No GGUF model files were returned for this repository.</div>'}</div></div><aside class="modal-side"><dl class="technical-dl"><div><dt>Publisher</dt><dd>${esc(m.author)}</dd></div><div><dt>Task</dt><dd>${esc(m.pipeline_tag||'not specified')}</dd></div><div><dt>Downloads</dt><dd>${fmtCount(m.downloads)}</dd></div><div><dt>Likes</dt><dd>${m.likes||0}</dd></div><div><dt>Gated</dt><dd>${m.gated?'Yes':'No'}</dd></div><div><dt>Fit estimate</dt><dd>${fitLabel(c.level)}</dd></div></dl>${(m.projectors||[]).length?`<label>Multimodal projector<select class="projector-select" id="projectorSelect">${projectorOptions.join('')}</select></label>`:''}<div class="button-row"><button class="ghost" id="openHfSource">Open source</button></div></aside></div>`;
 $('#openHfSource').onclick=()=>window.botconnector.openExternal(m.homepage);$$('[data-download-group]').forEach(btn=>btn.onclick=()=>startDownload(Number(btn.dataset.downloadGroup)));
}
async function startDownload(index){const m=currentDetails,g=m?.files?.[index];if(!g)return;let projector=null;const ps=$('#projectorSelect');if(ps&&ps.value!=='')projector=m.projectors[Number(ps.value)]||null;try{const job=await window.botconnector.downloadModel({repoId:m.id,group:g,projector,metadata:{capabilities:m.capabilities,pipeline_tag:m.pipeline_tag}});upsertDownload(job);$('#modelModal').hidden=true;navigate('downloads')}catch(e){alert(`Download failed to start: ${e.message||e}`)}}
function upsertDownload(job){const i=state.downloads.findIndex(x=>x.id===job.id);if(i>=0)state.downloads[i]=job;else state.downloads.unshift(job);renderGlobal();if(job.status==='completed')refreshInstalled()}
function renderDownloads(){const root=$('#downloadJobs');if(!root)return;root.innerHTML=state.downloads.length?state.downloads.map(j=>{const p=safePct(j.downloadedBytes,j.totalBytes);return `<article class="download-job"><div class="download-head"><div><b>${esc(j.repoId)} · ${esc(j.quant)}</b><span> ${esc(j.status)}</span></div><span>${fmtBytes(j.downloadedBytes)} / ${fmtBytes(j.totalBytes)}</span></div><progress max="100" value="${p}"></progress><div class="download-foot"><span>${j.bytesPerSecond?`${fmtBytes(j.bytesPerSecond)}/s`:''}${j.error?` · ${esc(j.error)}`:''}</span><div class="download-actions">${['downloading','verifying'].includes(j.status)?`<button class="ghost" data-pause="${j.id}">Pause</button><button class="danger" data-cancel="${j.id}">Cancel</button>`:['paused','failed','cancelled'].includes(j.status)?`<button class="primary" data-resume="${j.id}">Resume</button>`:''}</div></div></article>`}).join(''):'<div class="empty">No download jobs in this session.</div>';root.querySelectorAll('[data-pause]').forEach(b=>b.onclick=()=>window.botconnector.pauseDownload(b.dataset.pause));root.querySelectorAll('[data-resume]').forEach(b=>b.onclick=()=>window.botconnector.resumeDownload(b.dataset.resume));root.querySelectorAll('[data-cancel]').forEach(b=>b.onclick=()=>window.botconnector.cancelDownload(b.dataset.cancel))}
async function refreshInstalled(){state.installed=await window.botconnector.installedModels();renderGlobal()}
function installedRow(m){const gb=fmtBytes(m.size);return `<article class="model-row"><div class="model-icon">▣</div><div class="model-main"><div class="model-title-line"><h3>${esc(m.repoId||m.name)}</h3><span class="fit">Installed</span></div><div class="caps">${caps(m.capabilities)}</div><div class="model-meta"><span>${esc(m.quant||'GGUF')}</span><span>${gb}</span><span>${esc(m.name)}</span>${m.projector?'<span>multimodal projector</span>':''}</div></div><div class="model-action"><button class="primary" data-run-model="${esc(m.path)}">Run</button><button class="ghost" data-show-model="${esc(m.path)}">Show</button><button class="danger" data-delete-model="${esc(m.dir)}">Delete</button></div></article>`}
function renderInstalled(){const root=$('#installedModels');if(!root)return;root.innerHTML=state.installed.length?state.installed.map(installedRow).join(''):'<div class="empty">No downloaded GGUF models were found in the configured directory.</div>';root.querySelectorAll('[data-run-model]').forEach(b=>b.onclick=()=>runInstalled(b.dataset.runModel));root.querySelectorAll('[data-show-model]').forEach(b=>b.onclick=()=>window.botconnector.revealModel(b.dataset.showModel));root.querySelectorAll('[data-delete-model]').forEach(b=>b.onclick=async()=>{if(!confirm('Delete this installed model directory?'))return;state.installed=await window.botconnector.deleteModel(b.dataset.deleteModel);renderGlobal()})}
async function runInstalled(p){const m=state.installed.find(x=>x.path===p);if(!m)return;if(!state.managedRuntime?.installed){navigate('runtime');$('#runtimeInstallInfo').textContent='Install the managed llama.cpp runtime before launching a downloaded model.';return}try{const backend=resolvedBackend(),context=Number($('#runtimeContext').value||8192);await window.botconnector.startInstalled({modelPath:m.path,projector:m.projector,backend,context,embedding:Boolean(m.capabilities?.embeddings)});state.runtime=await window.botconnector.runtimeStatus();renderGlobal();navigate(m.capabilities?.embeddings?'runtime':'chat')}catch(e){navigate('runtime');$('#runtimeInstallInfo').textContent=`Start failed: ${e.message||e}`}}
function renderRuntime(){if(!$('#runtimeDetailStatus'))return;$('#runtimeBackend').value=state.settings?.runtimeBackend||'auto';$('#managedBinary').textContent=state.managedRuntime?.binary||'Not installed';$('#runtimeDetailStatus').textContent=state.runtime?.running?`Running · PID ${state.runtime.pid}`:'Stopped';$('#runtimeDetailModel').textContent=state.runtime?.running?(state.runtime.modelPath?.split(/[\\/]/).pop()||'—'):'—';$('#stopRuntime').disabled=!state.runtime?.running;}
function renderSettings(){$('#settingsModelsDir').textContent=state.settings?.modelsDir||'—';$('#hfTokenNote').textContent=state.settings?.hfTokenConfigured?'Encrypted token is configured.':'Public repositories do not require a token.';$('#languageSelect').value=state.settings?.language||'system'}
function renderChatHeader(){$('#chatRuntimeLabel').textContent=state.runtime?.running?`Active: ${state.runtime.modelPath?.split(/[\\/]/).pop()||'local model'} · http://127.0.0.1:${state.runtime.port||11435}`:'Start a local model before sending messages.'}
function renderChat(){const box=$('#chatMessages');box.innerHTML=chatMessages.length?chatMessages.map(m=>`<div class="message ${m.role}"><small>${m.role==='user'?'YOU':m.role==='tool'?'TOOL RESULT':'LOCAL MODEL'}</small>${m.reasoning?`<details class="reasoning"><summary>Reasoning trace (model-exposed)</summary><div>${esc(m.reasoning)}</div></details>`:''}${(m.toolCalls||[]).map(t=>`<div class="tool-call"><b>🔧 Tool call: ${esc(t.function?.name||t.name||'?')}</b><code>${esc(typeof t.function?.arguments==='string'?t.function.arguments:JSON.stringify(t.input||t.function?.arguments||{}))}</code><span class="technical-note">No automatic execution — the model only proposed this call.</span></div>`).join('')}<div>${esc(m.content)}</div></div>`).join(''):'<div class="empty">No messages.</div>';box.scrollTop=box.scrollHeight}
function navigate(v){currentView=v;$$('.view').forEach(x=>x.classList.remove('active-view'));$(`#view-${v}`).classList.add('active-view');$$('.sidebar [data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===v));setHeader(v);if(v==='discover'&&!discoverAll.length)loadDiscover('');if(v==='runtime')refreshLogs();if(v==='installed')refreshInstalled()}
$$('.sidebar [data-view], [data-view].ghost').forEach(b=>b.addEventListener('click',()=>navigate(b.dataset.view)));
$$('[data-cap]').forEach(b=>b.onclick=()=>{cap=b.dataset.cap;$$('[data-cap]').forEach(x=>x.classList.toggle('active',x===b));renderDiscover()});
$$('[data-discover-tab]').forEach(b=>b.onclick=()=>{discoverTab=b.dataset.discoverTab;$$('[data-discover-tab]').forEach(x=>x.classList.toggle('active',x===b));renderDiscover()});
$('#discoverSearchBtn').onclick=()=>loadDiscover($('#discoverSearch').value.trim());$('#discoverSearch').onkeydown=e=>{if(e.key==='Enter')loadDiscover(e.target.value.trim())};$('#discoverSearch').oninput=()=>renderDiscover();$('#discoverClear').onclick=()=>{$('#discoverSearch').value='';loadDiscover('')};
$('#closeModal').onclick=()=>$('#modelModal').hidden=true;$('#modelModal').onclick=e=>{if(e.target.id==='modelModal')e.currentTarget.hidden=true};
$('#refreshInstalled').onclick=refreshInstalled;
$('#temperature').oninput=e=>$('#tempValue').textContent=e.target.value;
$('#attachImage').onclick=async()=>{chatAttachment=await window.botconnector.pickImage();$('#attachmentLine').hidden=!chatAttachment;$('#attachmentLine').textContent=chatAttachment?`Image attached: ${chatAttachment.name}`:''};
$('#clearChat').onclick=()=>{chatMessages=[];chatAttachment=null;$('#attachmentLine').hidden=true;renderChat()};
function streamMessage(messages){return new Promise((resolve,reject)=>{chatRequestId=crypto.randomUUID();let text='',reasoning='';const toolCalls=[];chatMessages.push({role:'assistant',content:'',reasoning:'',toolCalls});renderChat();const cur=()=>chatMessages[chatMessages.length-1];const cleanup=()=>{offDelta();offReason();offTool();offDone();offErr()};const onDelta=p=>{if(p.requestId!==chatRequestId)return;text+=p.delta;cur().content=text;renderChat()};const onReason=p=>{if(p.requestId!==chatRequestId)return;reasoning+=p.delta;cur().reasoning=reasoning;renderChat()};const onTool=p=>{if(p.requestId!==chatRequestId)return;mergeToolCall(toolCalls,p.toolCall);cur().toolCalls=toolCalls.slice();renderChat()};const onDone=p=>{if(p.requestId!==chatRequestId)return;cleanup();resolve({text,reasoning,toolCalls})};const onErr=p=>{if(p.requestId!==chatRequestId)return;cleanup();chatMessages.pop();renderChat();reject(new Error(p.error))};const offDelta=window.botconnector.onChatDelta(onDelta),offReason=window.botconnector.onChatReasoning(onReason),offTool=window.botconnector.onChatToolCall(onTool),offDone=window.botconnector.onChatDone(onDone),offErr=window.botconnector.onChatError(onErr);window.botconnector.streamChat({requestId:chatRequestId,messages,options:{temperature:Number($('#temperature').value)}})})}
function mergeToolCall(list,tc){if(!tc||typeof tc!=='object')return;const idx=Number(tc.index||0);const cur=list[idx]||(list[idx]={function:{name:'',arguments:''}});const fn=tc.function||{};if(fn.name)cur.function.name=(cur.function.name||'')+fn.name;if(typeof fn.arguments==='string')cur.function.arguments=(cur.function.arguments||'')+fn.arguments;if(tc.id)cur.id=tc.id;}
$('#chatSend').onclick=async()=>{const input=$('#chatInput'),text=input.value.trim();if(!text)return;if(!state.runtime?.running){navigate('runtime');return}let content=text;if(chatAttachment)content=[{type:'text',text},{type:'image_url',image_url:{url:chatAttachment.dataUrl}}];chatMessages.push({role:'user',content:text});input.value='';renderChat();$('#chatNotice').textContent='Generating…';$('#chatSend').disabled=true;try{const payload=chatMessages.filter(m=>m.role!=='assistant'||m.content||(m.toolCalls||[]).length).map((m,i)=>{const base=i===chatMessages.length-1&&chatAttachment?{role:'user',content}:m.role==='assistant'?{role:'assistant',content:m.content||null}:m;if(m.role==='assistant'&&(m.toolCalls||[]).length)base.tool_calls=m.toolCalls.map(t=>({id:t.id||undefined,type:'function',function:{name:t.function?.name||t.name,arguments:typeof t.function?.arguments==='string'?t.function.arguments:JSON.stringify(t.input||{})}}));return base});await streamMessage(payload);$('#chatNotice').textContent='Done.';chatAttachment=null;$('#attachmentLine').hidden=true}catch(e){$('#chatNotice').textContent=`Chat failed: ${e.message||e}`}finally{$('#chatSend').disabled=false}};
$('#chatInput').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();$('#chatSend').click()}};
$('#checkRuntime').onclick=async()=>{try{const r=await window.botconnector.latestRuntime();$('#runtimeInstallInfo').textContent=`Newest usable release: ${r.tag}${r.prerelease?' (prerelease)':''} · ${r.assets.length} published assets`}catch(e){$('#runtimeInstallInfo').textContent=`Check failed: ${e.message||e}`}};
$('#installRuntime').onclick=async()=>{let backend=$('#runtimeBackend').value;if(backend==='auto')backend=resolvedBackend();$('#runtimeProgress').hidden=false;$('#runtimeInstallInfo').textContent=`Installing ${backend} runtime…`;try{await window.botconnector.setSettings({runtimeBackend:$('#runtimeBackend').value});state.settings=await window.botconnector.getSettings();const r=await window.botconnector.installRuntime({backend});state.managedRuntime=await window.botconnector.managedRuntime();$('#runtimeInstallInfo').textContent=`Installed ${r.release} · ${r.backend}`;renderGlobal()}catch(e){$('#runtimeInstallInfo').textContent=`Install failed: ${e.message||e}`}};
window.botconnector.onRuntimeInstallProgress(p=>{if(!$('#runtimeProgress'))return;$('#runtimeProgress').hidden=false;const pct=safePct(p.downloadedBytes,p.totalBytes);$('#runtimeProgressPct').textContent=p.status==='completed'?'100%':`${pct}%`;$('#runtimeProgressBar').value=p.status==='completed'?100:pct;$('#runtimeProgressLabel').textContent=p.status==='completed'?`Installed ${p.release}`:`${p.asset||'runtime'} · ${fmtBytes(p.downloadedBytes)}/${fmtBytes(p.totalBytes)}`});
$('#stopRuntime').onclick=async()=>{await window.botconnector.stopRuntime();state.runtime=await window.botconnector.runtimeStatus();renderGlobal();refreshLogs()};
async function refreshLogs(){const lines=await window.botconnector.runtimeLogs();$('#runtimeLogs').textContent=lines.length?lines.join('\n'):'No runtime log.'}
$('#refreshLogs').onclick=refreshLogs;
$('#pickBinary').onclick=async()=>{const p=await window.botconnector.pickBinary();if(p)$('#manualBinary').value=p};$('#pickModel').onclick=async()=>{const p=await window.botconnector.pickModel();if(p)$('#manualModel').value=p};$('#manualStart').onclick=async()=>{try{await window.botconnector.startRuntime({binary:$('#manualBinary').value,modelPath:$('#manualModel').value,port:11435,gpuLayers:resolvedBackend()==='cpu'?0:999,context:Number($('#runtimeContext').value||8192)});state.runtime=await window.botconnector.runtimeStatus();$('#manualStatus').textContent='Runtime started.';renderGlobal()}catch(e){$('#manualStatus').textContent=`Start failed: ${e.message||e}`}};
$('#pickModelsDir').onclick=async()=>{const r=await window.botconnector.pickModelsDir();if(r){state.settings=await window.botconnector.getSettings();state.installed=r.installed||[];renderGlobal()}};
$('#saveHfToken').onclick=async()=>{try{await window.botconnector.setHfToken($('#hfTokenInput').value);$('#hfTokenInput').value='';state.settings=await window.botconnector.getSettings();renderSettings()}catch(e){$('#hfTokenNote').textContent=`Failed: ${e.message||e}`}};$('#clearHfToken').onclick=async()=>{await window.botconnector.setHfToken('');state.settings=await window.botconnector.getSettings();renderSettings()};
$('#languageSelect').onchange=async e=>{await window.botconnector.setSettings({language:e.target.value});state.settings=await window.botconnector.getSettings();applyLanguage()};
window.botconnector.onDownloadProgress(job=>upsertDownload(job));
(async()=>{try{state=await window.botconnector.overview();applyLanguage();renderGlobal();loadDiscover('')}catch(e){console.error(e);$('#sideDevice').textContent='Initialization failed';$('#sideMemory').textContent=String(e.message||e)}})();
