(()=>{
const d={
 en:{nav:{home:'Home',chat:'Chat',discover:'Discover',installed:'Installed',downloads:'Downloads',cloud:'Cloud',runtime:'Runtime',developer:'Developer',mcp:'Tools / MCP',settings:'Settings'},headers:{home:['Home','Runtime, models, and local API state'],chat:['Chat','Streaming inference through the active local runtime'],discover:['Discover','Live Hugging Face GGUF catalog'],installed:['Installed','Models available on local storage'],downloads:['Downloads','Model transfer jobs and progress'],cloud:['Cloud','Hosted route contract and status'],runtime:['Runtime','Managed llama.cpp installation and process state'],developer:['Developer','Local API endpoints and compatibility'],mcp:['Tools / MCP','Safe local tool servers and permissions'],settings:['Settings','Storage, Hugging Face access, and interface']},status:{stopped:'Runtime stopped',running:'Runtime running'}},
 id:{nav:{home:'Home',chat:'Chat',discover:'Discover',installed:'Terpasang',downloads:'Unduhan',cloud:'Cloud',runtime:'Runtime',developer:'Developer',mcp:'Tools / MCP',settings:'Pengaturan'},headers:{home:['Home','Status runtime, model, dan API lokal'],chat:['Chat','Inference streaming melalui runtime lokal aktif'],discover:['Discover','Katalog GGUF Hugging Face secara live'],installed:['Terpasang','Model yang tersedia di penyimpanan lokal'],downloads:['Unduhan','Job transfer model dan progres'],cloud:['Cloud','Kontrak route model hosted dan status'],runtime:['Runtime','Instalasi llama.cpp terkelola dan status proses'],developer:['Developer','Endpoint API lokal dan kompatibilitas'],mcp:['Tools / MCP','Server tool lokal dan permission'],settings:['Pengaturan','Penyimpanan, akses Hugging Face, dan antarmuka']},status:{stopped:'Runtime berhenti',running:'Runtime aktif'}}
};
function resolve(sel,preferred=[]){if(sel==='en'||sel==='id')return sel;const x=String(preferred[0]||navigator.language||'en').toLowerCase();return x.startsWith('id')?'id':'en'}
function t(lang,path){return path.split('.').reduce((a,k)=>a?.[k],d[lang]||d.en)??path}
window.BotI18n={d,resolve,t};
})();
