const {contextBridge,ipcRenderer}=require('electron');
contextBridge.exposeInMainWorld('botconnector',{
  overview:()=>ipcRenderer.invoke('system:overview'),openExternal:u=>ipcRenderer.invoke('system:open-external',u),
  getSettings:()=>ipcRenderer.invoke('settings:get'),setSettings:v=>ipcRenderer.invoke('settings:set',v),  setHfToken:t=>ipcRenderer.invoke('settings:set-hf-token',t),ensureApiToken:()=>ipcRenderer.invoke('settings:ensure-api-token'),clearApiToken:()=>ipcRenderer.invoke('settings:clear-api-token'),pickModelsDir:()=>ipcRenderer.invoke('settings:pick-models-dir'),
  searchModels:i=>ipcRenderer.invoke('models:search-online',i),modelDetails:id=>ipcRenderer.invoke('models:details',id),installedModels:()=>ipcRenderer.invoke('models:installed'),revealModel:p=>ipcRenderer.invoke('models:reveal',p),deleteModel:d=>ipcRenderer.invoke('models:delete',d),downloadModel:p=>ipcRenderer.invoke('models:download',p),
  downloads:()=>ipcRenderer.invoke('downloads:list'),pauseDownload:id=>ipcRenderer.invoke('downloads:pause',id),resumeDownload:id=>ipcRenderer.invoke('downloads:resume',id),cancelDownload:id=>ipcRenderer.invoke('downloads:cancel',id),onDownloadProgress:cb=>ipcRenderer.on('download:progress',(_e,p)=>cb(p)),
  pickBinary:()=>ipcRenderer.invoke('runtime:pick-binary'),pickModel:()=>ipcRenderer.invoke('runtime:pick-model'),latestRuntime:()=>ipcRenderer.invoke('runtime:latest'),resolveRuntime:c=>ipcRenderer.invoke('runtime:resolve',c),verifyRuntime:()=>ipcRenderer.invoke('runtime:verify'),managedRuntime:()=>ipcRenderer.invoke('runtime:managed-status'),installRuntime:c=>ipcRenderer.invoke('runtime:install',c),startRuntime:c=>ipcRenderer.invoke('runtime:start',c),startInstalled:c=>ipcRenderer.invoke('runtime:start-installed',c),stopRuntime:()=>ipcRenderer.invoke('runtime:stop'),runtimeStatus:()=>ipcRenderer.invoke('runtime:status'),runtimeLogs:()=>ipcRenderer.invoke('runtime:logs'),onRuntimeInstallProgress:cb=>ipcRenderer.on('runtime:install-progress',(_e,p)=>cb(p)),
  chat:m=>ipcRenderer.invoke('chat:complete',m),pickImage:()=>ipcRenderer.invoke('chat:pick-image'),streamChat:p=>ipcRenderer.send('chat:stream',p),onChatDelta:cb=>{const h=(_e,p)=>cb(p);ipcRenderer.on('chat:delta',h);return()=>ipcRenderer.removeListener('chat:delta',h)},onChatReasoning:cb=>{const h=(_e,p)=>cb(p);ipcRenderer.on('chat:reasoning',h);return()=>ipcRenderer.removeListener('chat:reasoning',h)},onChatToolCall:cb=>{const h=(_e,p)=>cb(p);ipcRenderer.on('chat:toolcall',h);return()=>ipcRenderer.removeListener('chat:toolcall',h)},onChatDone:cb=>{const h=(_e,p)=>cb(p);ipcRenderer.on('chat:done',h);return()=>ipcRenderer.removeListener('chat:done',h)},onChatError:cb=>{const h=(_e,p)=>cb(p);ipcRenderer.on('chat:error',h);return()=>ipcRenderer.removeListener('chat:error',h)}
});
